# Exploratory Data Analysis of Industry Dataset

# 1. Import Libraries

In [39]:
# Numerical Operations
import numpy as np

# Data Analysis
import pandas as pd

# Visualizatins
import matplotlib.pyplot as plt
import seaborn as sns

# 2. Load Dataset

In [40]:
df = pd.read_csv("INDUSTRY.csv")

In [41]:
df

,id,company_name,industry,country,employee_count,annual_revenue_million,profit_margin_percent,founded_year,customer_count,market_rating,created_date,region
0,1,FinTrust_1,Finance,India,535,539.38,40.42,2010,81191,0.7,13-10-2025,Asia
1,2,TechNova_2,Technology,Germany,3806,852.42,39.55,2010,92162,3.4,01-12-2025,Europe
2,3,RetailHub_3,Retail,Canada,2779,257.11,23.68,1996,27532,2.9,04-05-2025,North America
3,4,BuildWorks_4,Manufacturing,USA,835,309.14,31.31,1993,90815,0.9,01-02-2026,North America
4,5,MediCorp_5,Healthcare,India,4490,988.68,43.65,1996,850,0.5,29-06-2025,Asia
...,...,...,...,...,...,...,...,...,...,...,...,...
14995,14996,FinTrust_14996,Finance,USA,2814,369.06,25.59,2011,52295,1.6,25-08-2024,North America
14996,14997,TechNova_14997,Technology,India,3977,758.47,32.68,2019,4118,0.3,30-04-2024,Asia
14997,14998,RetailHub_14998,Retail,Germany,454,859.89,15.36,1999,54468,0.1,05-04-2024,Europe
14998,14999,BuildWorks_14999,Manufacturing,Canada,2787,111.92,41.82,2019,74866,1.9,30-12-2024,North America
14999,15000,MediCorp_15000,Healthcare,USA,1473,879.67,29.31,2003,12998,2.0,14-03-2024,North America

In [42]:
df.head()

,id,company_name,industry,country,employee_count,annual_revenue_million,profit_margin_percent,founded_year,customer_count,market_rating,created_date,region
0,1,FinTrust_1,Finance,India,535,539.38,40.42,2010,81191,0.7,13-10-2025,Asia
1,2,TechNova_2,Technology,Germany,3806,852.42,39.55,2010,92162,3.4,01-12-2025,Europe
2,3,RetailHub_3,Retail,Canada,2779,257.11,23.68,1996,27532,2.9,04-05-2025,North America
3,4,BuildWorks_4,Manufacturing,USA,835,309.14,31.31,1993,90815,0.9,01-02-2026,North America
4,5,MediCorp_5,Healthcare,India,4490,988.68,43.65,1996,850,0.5,29-06-2025,Asia

In [43]:
df.tail()

,id,company_name,industry,country,employee_count,annual_revenue_million,profit_margin_percent,founded_year,customer_count,market_rating,created_date,region
14995,14996,FinTrust_14996,Finance,USA,2814,369.06,25.59,2011,52295,1.6,25-08-2024,North America
14996,14997,TechNova_14997,Technology,India,3977,758.47,32.68,2019,4118,0.3,30-04-2024,Asia
14997,14998,RetailHub_14998,Retail,Germany,454,859.89,15.36,1999,54468,0.1,05-04-2024,Europe
14998,14999,BuildWorks_14999,Manufacturing,Canada,2787,111.92,41.82,2019,74866,1.9,30-12-2024,North America
14999,15000,MediCorp_15000,Healthcare,USA,1473,879.67,29.31,2003,12998,2.0,14-03-2024,North America

# 3. Initial Data Inspection

In [44]:
df.shape

(15000, 12)

In [45]:
df.columns

Index(['id', 'company_name', 'industry', 'country', 'employee_count',
       'annual_revenue_million', 'profit_margin_percent', 'founded_year',
       'customer_count', 'market_rating', 'created_date', 'region'],
      dtype='object')

In [46]:
df.dtypes

id                          int64
company_name               object
industry                   object
country                    object
employee_count              int64
annual_revenue_million    float64
profit_margin_percent     float64
founded_year                int64
customer_count              int64
market_rating             float64
created_date               object
region                     object
dtype: object

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      15000 non-null  int64
 1   company_name            15000 non-null  object
 2   industry                15000 non-null  object
 3   country                 15000 non-null  object
 4   employee_count          15000 non-null  int64
 5   annual_revenue_million  15000 non-null  float64
 6   profit_margin_percent   15000 non-null  float64
 7   founded_year            15000 non-null  int64
 8   customer_count          15000 non-null  int64
 9   market_rating           15000 non-null  float64
 10  created_date            15000 non-null  object
 11  region                  15000 non-null  object
dtypes: float64(3), int64(4), object(5)
memory usage: 1.4+ MB

In [48]:
# check missing values

df.isnull().sum()

id                        0
company_name              0
industry                  0
country                   0
employee_count            0
annual_revenue_million    0
profit_margin_percent     0
founded_year              0
customer_count            0
market_rating             0
created_date              0
region                    0
dtype: int64

In [49]:
# Check Duplicate Records

df.duplicated().sum()

np.int64(0)

In [50]:
# Describe() ==> Generates statistics for numerical columns like count,mean,min,max,25% etc

df.describe()

,id,employee_count,annual_revenue_million,profit_margin_percent,founded_year,customer_count,market_rating
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,7500.500000,2606.862067,549.732707,25.012019,2004.374000,50449.251867,2.513780
std,4330.271354,1430.562513,288.244128,11.526187,8.606687,28744.638830,1.447998
min,1.000000,100.000000,50.160000,5.000000,1990.000000,500.000000,0.000000
25%,3750.750000,1379.000000,299.915000,15.050000,1997.000000,25676.250000,1.200000
50%,7500.500000,2587.000000,543.920000,24.910000,2004.000000,50726.500000,2.500000
75%,11250.250000,3839.000000,797.570000,35.100000,2012.000000,75271.250000,3.800000
max,15000.000000,5099.000000,1049.960000,45.000000,2019.000000,100495.000000,5.000000

In [51]:
# Analyzes text columns

df.describe(include='object')

          company_name industry country created_date         region
count            15000    15000   15000        15000          15000
unique           15000        5       4          790              3
top     MediCorp_15000  Finance   India   27-01-2024  North America
freq                 1     3000    3750           32           7500

In [52]:
"""
 Wrong data type in dataset ==> column --> created_date is stoed as object which means plain text. it should actually be DATETIME type because it
 stores dates.

 if dates remain as object (as text ):
  -- time analysis become difficult
  -- sorting issues occur
  -- date calculations fail.
"""

df['created_date'] = pd.to_datetime(df['created_date'],dayfirst=True)

In [53]:
print(df['created_date'].dtypes)

datetime64[ns]

# 4. Data Cleaning & Preparation

In [54]:
# We create a backup copy

df_clean = df.copy()

In [55]:
# verify missing values again
# get 0 missing values in all columns

df_clean.isnull().sum()

id                        0
company_name              0
industry                  0
country                   0
employee_count            0
annual_revenue_million    0
profit_margin_percent     0
founded_year              0
customer_count            0
market_rating             0
created_date              0
region                    0
dtype: int64

In [56]:
# verify duplicates again
# no duplicates rows

df_clean.duplicated().sum()

np.int64(0)

In [57]:
# check data types again

df_clean.dtypes

id                                 int64
company_name                      object
industry                          object
country                           object
employee_count                     int64
annual_revenue_million           float64
profit_margin_percent            float64
founded_year                       int64
customer_count                     int64
market_rating                    float64
created_date              datetime64[ns]
region                            object
dtype: object

In [58]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15000 entries, 0 to 14999
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   id                      15000 non-null  int64
 1   company_name            15000 non-null  object
 2   industry                15000 non-null  object
 3   country                 15000 non-null  object
 4   employee_count          15000 non-null  int64
 5   annual_revenue_million  15000 non-null  float64
 6   profit_margin_percent   15000 non-null  float64
 7   founded_year            15000 non-null  int64
 8   customer_count          15000 non-null  int64
 9   market_rating           15000 non-null  float64
 10  created_date            15000 non-null  datetime64[ns]
 11  region                  15000 non-null  object
dtypes: datetime64[ns](1), float64(3), int64(4), object(4)
memory usage: 1.4+ MB

In [59]:
df_clean.head()

,id,company_name,industry,country,employee_count,annual_revenue_million,profit_margin_percent,founded_year,customer_count,market_rating,created_date,region
0,1,FinTrust_1,Finance,India,535,539.38,40.42,2010,81191,0.7,2025-10-13,Asia
1,2,TechNova_2,Technology,Germany,3806,852.42,39.55,2010,92162,3.4,2025-12-01,Europe
2,3,RetailHub_3,Retail,Canada,2779,257.11,23.68,1996,27532,2.9,2025-05-04,North America
3,4,BuildWorks_4,Manufacturing,USA,835,309.14,31.31,1993,90815,0.9,2026-02-01,North America
4,5,MediCorp_5,Healthcare,India,4490,988.68,43.65,1996,850,0.5,2025-06-29,Asia

# 5. Univariate Analysis

In [63]:
numerical_columns = [
    'employee_count',
    'annual_revenue_million',
    'profit_margin_percent',
    'founded_year',
    'customer_count',
    'market_rating'
]

In [64]:
df_clean[numerical_columns].describe()

,employee_count,annual_revenue_million,profit_margin_percent,founded_year,customer_count,market_rating
count,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000,15000.000000
mean,2606.862067,549.732707,25.012019,2004.374000,50449.251867,2.513780
std,1430.562513,288.244128,11.526187,8.606687,28744.638830,1.447998
min,100.000000,50.160000,5.000000,1990.000000,500.000000,0.000000
25%,1379.000000,299.915000,15.050000,1997.000000,25676.250000,1.200000
50%,2587.000000,543.920000,24.910000,2004.000000,50726.500000,2.500000
75%,3839.000000,797.570000,35.100000,2012.000000,75271.250000,3.800000
max,5099.000000,1049.960000,45.000000,2019.000000,100495.000000,5.000000

In [65]:
# Calculate mean

df_clean[numerical_columns].mean()

employee_count             2606.862067
annual_revenue_million      549.732707
profit_margin_percent        25.012019
founded_year               2004.374000
customer_count            50449.251867
market_rating                 2.513780
dtype: float64

In [ ]:
""" Mean is useful for :
    -- understanding central tendency
    -- detecting unusual values
    -- comparing columns
    -- summarizing dataset
But mean can be affected be outliers.
I observe that if average revenue is high --> The dataset indicates moderate to strong business performance based on average revenue and
                                              profit margin values.

"""

In [ ]:
"""

OBSERVATIONS FROM MEAN ANALYSIS

1. The average employee_count is around 2607 employees,
   which indicates that most companies in the dataset are medium to large-sized organizations.

2. The average_annual_million revenue is approximately 549.73 million,
   showing that companies in the dataset generate strong business revenue overall.

3. The average profit_margin_percent is around 25%,
   which suggests that companies maintain healthy profitability.

4. The average founded_year is 2004,
   meaning most companies are relatively modern businesses established after 2000.

5. The average customer_count is about 50,449 customers,
   indicating that companies serve a large customer base.

6. The average market_rating is 2.51 out of 5,
   which suggests average market performance overall.

7. Mean values may be affected by outliers.
   For example, a company with extremely high revenue or employee count
   can increase the overall average significantly.

"""

In [71]:
# Calculate Meadian

df_clean[numerical_columns].median()

employee_count             2587.00
annual_revenue_million      543.92
profit_margin_percent        24.91
founded_year               2004.00
customer_count            50726.50
market_rating                 2.50
dtype: float64